# Generated by Django 3.2.7 on 2021-11-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0003_auto_20211109_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(help_text='Digite o nome da disciplina', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='topico',
            name='nome',
            field=models.CharField(help_text='Digite o nome do tópico', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(help_text='Digite o email do usuário', max_length=254, unique=True),
        ),
    ]
