# Generated by Django 3.2.7 on 2021-11-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0005_auto_20211110_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='heitor@ufg.br', help_text='Digite o email do usuário', max_length=254),
        ),
    ]
